language: node_js

matrix:
  include:
  - os: linux
    node_js: '6'
    sudo: false
    dist: trusty
  - os: osx
    node_js: '6'
    osx_image: xcode8.3

addons:
  apt:
    packages:
    - libudev-dev
    - rpm

git:
  depth: 5

cache:
  directories:
  - $HOME/.electron
  - node_modules
  yarn: true

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
- export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn

before_script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3; # give xvfb some time to start
  fi

script: ./tools/travis.sh
