language: node_js

matrix:
  include:
  - os: linux
    node_js: '6'
    sudo: false
    dist: trusty
  - os: osx
    node_js: '6'
    osx_image: xcode8.3

addons:
  apt:
    packages:
    - libudev-dev
    - rpm

git:
  depth: 5

cache:
  directories:
  - $HOME/.electron
  - node_modules
  yarn: true

install:
- yarn install

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi # give xvfb some time to start

script: ./tools/travis.sh
