version: '{build}'

platform:
- x64

clone_depth: 5
cache:
- '%LOCALAPPDATA%\Yarn'
- '%USERPROFILE%\.electron'
- node_modules

init:
- git config --global core.autocrlf input
- git config --system core.longpaths true

install:
- ps: Install-Product node 7.10.1 x64
- yarn install

build_script:
- yarn run build
- ps: |
    $tags=(git tag --points-at $env:APPVEYOR_REPO_COMMIT)
    if ($tags) {
      yarn run electron-dist
      $config = New-TemporaryFile
      echo $env:GOOGLE_CLOUD_STORAGE_CONFIG | node -e "console.log(new Buffer ('$env:GOOGLE_CLOUD_STORAGE_CONFIG', 'base64').toString('utf8').trim())" > $config
      (Get-Content -Path $config) | %{ $_.Replace("\xEF\xBB\xBF", "") } | Set-Content -Path $config
      foreach ($tag in $tags) {
        foreach ($file in (Get-ChildItem -Path packages/xod-client-electron/dist -File)) {
          node tools/electron-upload.js --config=$config --file=$($file.FullName) --tag=$tag
        }
      }
    }

test: off
