version: '{build}'

platform:
- x64

clone_depth: 5
cache:
- '%LOCALAPPDATA%\Yarn'
- '%USERPROFILE%\.electron'
- node_modules

init:
- git config --global core.autocrlf input
- git config --system core.longpaths true

install:
- ps: Install-Product node 7.10.1 x64
- yarn install

build_script:
- yarn run build
- ps: . .\tools\appveyor.ps1

test: off
